algoritmo "semnome"
var
    r: caractere
    n, s:inteiro
inicio
      r:= "s"      //sempre precisa registrar o valor da variavel auxiliar
      Repita
            escreva(" digite um valor inteiro: ")
            leia(n)
            s:= s + n
            escreva("voce deseja continuar[s/n]? ")
            leia(R)
      ate(r= "n")
      
      escreva("fim repeta! ")
fimalgoritmo
