algoritmo "Vetores"
var
   n: vetor[1..3] de inteiro
   i : inteiro
inicio
       //leia os valores para o Vetor
      para i := 1 ate 3 faca        //não precisa passa pq por defoun ele já pula um
           escreva("vetor_n",i, ":")
           leia(n[i])
      fimPara

      //mostre os valores para user
      para i:= 1 ate 3 faca
      escreva(i, n[i])
      fimPara

fimalgoritmo




      
      
      
      

