algoritmo "semnome"
var
     reais, valor_dolar, compra_dolar: real
inicio
      escreval("Quanto dinheiro voce tem na carteira: [em R$]")
      leia(reais)
      valor_dolar:= 3.45
      compra_dolar:= reais / valor_dolar
      escreval("Você pode comprar ", compra_dolar, " dolar.")
      
      
fimalgoritmo

//9) Faça um algoritmo que leia quanto dinheiro uma pessoa tem na carteira (em R$)
//e mostre quantos dólares ela pode comprar. Considere US$1,00 = R$3,45.
