algoritmo "Matrix de identidade s/matrix"
var

   i,j: inteiro
inicio
      para i:= 1 ate 3 faca
           para j:= 1 ate 3 faca
                se(i=j) entao       //[1,1] [2,2] [3,3]
                        escreva(1)
                senao
                     escreva(0)
                fimse
           fimpara
            escreval
      fimpara
fimalgoritmo
 
// 3] Escreva um algoritmo que gera uma matriz identidade de ordem 3 X 3.
 

